// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBusN7sTS3Io_F6hTalokpavNMj7Sw8PBM',
    appId: '1:628441589377:web:7617e59cc9168bd6a20f80',
    messagingSenderId: '628441589377',
    projectId: 'nadacilik-79969',
    authDomain: 'nadacilik-79969.firebaseapp.com',
    storageBucket: 'nadacilik-79969.firebasestorage.app',
    measurementId: 'G-6JDVX35X1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPJf83Vd0WC6EAnWY988D3PepikHgyjoo',
    appId: '1:628441589377:android:02cf8c559cfbc523a20f80',
    messagingSenderId: '628441589377',
    projectId: 'nadacilik-79969',
    storageBucket: 'nadacilik-79969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUT7fXq-ktijNC1AoRdHsqMmQ76IzjwT8',
    appId: '1:628441589377:ios:ecb44a7a9aa1ff13a20f80',
    messagingSenderId: '628441589377',
    projectId: 'nadacilik-79969',
    storageBucket: 'nadacilik-79969.firebasestorage.app',
    iosBundleId: 'com.example.projectuas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUT7fXq-ktijNC1AoRdHsqMmQ76IzjwT8',
    appId: '1:628441589377:ios:ecb44a7a9aa1ff13a20f80',
    messagingSenderId: '628441589377',
    projectId: 'nadacilik-79969',
    storageBucket: 'nadacilik-79969.firebasestorage.app',
    iosBundleId: 'com.example.projectuas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBusN7sTS3Io_F6hTalokpavNMj7Sw8PBM',
    appId: '1:628441589377:web:9a51512a1324d086a20f80',
    messagingSenderId: '628441589377',
    projectId: 'nadacilik-79969',
    authDomain: 'nadacilik-79969.firebaseapp.com',
    storageBucket: 'nadacilik-79969.firebasestorage.app',
    measurementId: 'G-J6DN0L6RDR',
  );
}
